[2025-03-21T19:05:13.350+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T19:05:14.296+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_openmeteo manual__2025-03-21T19:04:56.298692+00:00 [queued]>
[2025-03-21T19:05:14.507+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_openmeteo manual__2025-03-21T19:04:56.298692+00:00 [queued]>
[2025-03-21T19:05:14.521+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T19:05:15.334+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_weather_openmeteo> on 2025-03-21 19:04:56.298692+00:00
[2025-03-21T19:05:16.202+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=1466) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T19:05:16.338+0000] {standard_task_runner.py:72} INFO - Started process 1483 to run task
[2025-03-21T19:05:16.315+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'fetch_weather_openmeteo', 'manual__2025-03-21T19:04:56.298692+00:00', '--job-id', '143', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmp_frmxpv_']
[2025-03-21T19:05:16.449+0000] {standard_task_runner.py:105} INFO - Job 143: Subtask fetch_weather_openmeteo
[2025-03-21T19:05:18.684+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.fetch_weather_openmeteo manual__2025-03-21T19:04:56.298692+00:00 [running]> on host c25e9da6226b
[2025-03-21T19:05:29.383+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_openmeteo' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T19:04:56.298692+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T19:04:56.298692+00:00'
[2025-03-21T19:05:29.398+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T19:05:30.331+0000] {python.py:240} INFO - Done. Returned value was:                datetime  ...                                id
0   2025-03-22 00:00:00  ...  d141d7863df92d8589c38ada109e123d
1   2025-03-22 01:00:00  ...  9a76c33fd475d3dd15980ea9b0a6cf0f
2   2025-03-22 02:00:00  ...  bcecc2bcc96510667af038521c26a926
3   2025-03-22 03:00:00  ...  bfbcf0e41660e298c99997d3d53d7d1c
4   2025-03-22 04:00:00  ...  b50fabebec04f1c1ceae4f21a3c1fe62
..                  ...  ...                               ...
163 2025-03-28 19:00:00  ...  82bace31ccf535a12c230bd007e74e1f
164 2025-03-28 20:00:00  ...  68940bd488f1bb0d6b44dbc73aa42ae7
165 2025-03-28 21:00:00  ...  296be3fd5649c23a50f62c2636cca692
166 2025-03-28 22:00:00  ...  8757850d378d2c1fe6084046eab4c105
167 2025-03-28 23:00:00  ...  4dd715704408015a5d87f3a0c5434ae6

[168 rows x 6 columns]
[2025-03-21T19:05:30.541+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T19:05:30.545+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=fetch_weather_openmeteo, run_id=manual__2025-03-21T19:04:56.298692+00:00, execution_date=20250321T190456, start_date=20250321T190514, end_date=20250321T190530
[2025-03-21T19:05:30.689+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T19:05:31.529+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-03-21T19:05:31.602+0000] {taskinstance.py:3901} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-03-21T19:05:31.607+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
