[2025-03-22T00:00:02.251+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T00:00:02.273+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_tomorrow scheduled__2025-03-21T23:00:00+00:00 [queued]>
[2025-03-22T00:00:02.284+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.fetch_weather_tomorrow scheduled__2025-03-21T23:00:00+00:00 [queued]>
[2025-03-22T00:00:02.285+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-22T00:00:02.300+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_weather_tomorrow> on 2025-03-21 23:00:00+00:00
[2025-03-22T00:00:02.311+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5447) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-22T00:00:02.314+0000] {standard_task_runner.py:72} INFO - Started process 5453 to run task
[2025-03-22T00:00:02.313+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'fetch_weather_tomorrow', 'scheduled__2025-03-21T23:00:00+00:00', '--job-id', '188', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmpj73z_q0o']
[2025-03-22T00:00:02.317+0000] {standard_task_runner.py:105} INFO - Job 188: Subtask fetch_weather_tomorrow
[2025-03-22T00:00:02.395+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.fetch_weather_tomorrow scheduled__2025-03-21T23:00:00+00:00 [running]> on host c25e9da6226b
[2025-03-22T00:00:03.327+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='fetch_weather_tomorrow' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T23:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T23:00:00+00:00'
[2025-03-22T00:00:03.329+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T00:00:04.408+0000] {python.py:240} INFO - Done. Returned value was:                datetime  ...                                id
0   2025-03-22 00:00:00  ...  7538d7f45898dd9869b1dbb01d6b1645
1   2025-03-22 01:00:00  ...  d1eb62f94b4fcbbf59b97ea4de39b8b3
2   2025-03-22 02:00:00  ...  26f8d435fcd2aa9cc2d1583da2ac8fa9
3   2025-03-22 03:00:00  ...  eb42faae211398cdcbb90a26fdc32366
4   2025-03-22 04:00:00  ...  a18b86d83edecf96d945327ed8bb64ea
..                  ...  ...                               ...
116 2025-03-26 20:00:00  ...  7ed42922be6f89b113e1b4d45703533b
117 2025-03-26 21:00:00  ...  3d4c05af0f0dd36bbdb99fec3724077b
118 2025-03-26 22:00:00  ...  f8e46adba39ba3b0e30a921df3491f67
119 2025-03-26 23:00:00  ...  ed55b364a957e2276fee3b993254ac6c
120 2025-03-27 00:00:00  ...  4bd2a8a6a0ac1f90dd0747c863045e1c

[121 rows x 6 columns]
[2025-03-22T00:00:04.457+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T00:00:04.457+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=fetch_weather_tomorrow, run_id=scheduled__2025-03-21T23:00:00+00:00, execution_date=20250321T230000, start_date=20250322T000002, end_date=20250322T000004
[2025-03-22T00:00:04.499+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-22T00:00:04.705+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-22T00:00:04.707+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
