[2025-03-21T17:50:23.835+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T17:50:23.908+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-two-source.fetch_weather_openmeteo scheduled__2025-03-21T16:00:00+00:00 [queued]>
[2025-03-21T17:50:23.936+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-two-source.fetch_weather_openmeteo scheduled__2025-03-21T16:00:00+00:00 [queued]>
[2025-03-21T17:50:23.937+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T17:50:23.977+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_weather_openmeteo> on 2025-03-21 16:00:00+00:00
[2025-03-21T17:50:23.993+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=296) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T17:50:23.996+0000] {standard_task_runner.py:72} INFO - Started process 302 to run task
[2025-03-21T17:50:23.999+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-two-source', 'fetch_weather_openmeteo', 'scheduled__2025-03-21T16:00:00+00:00', '--job-id', '65', '--raw', '--subdir', 'DAGS_FOLDER/weather-two-source.py', '--cfg-path', '/tmp/tmp6abqdbbg']
[2025-03-21T17:50:24.006+0000] {standard_task_runner.py:105} INFO - Job 65: Subtask fetch_weather_openmeteo
[2025-03-21T17:50:24.450+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-two-source.fetch_weather_openmeteo scheduled__2025-03-21T16:00:00+00:00 [running]> on host c25e9da6226b
[2025-03-21T17:50:24.783+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-two-source' AIRFLOW_CTX_TASK_ID='fetch_weather_openmeteo' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T16:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-21T16:00:00+00:00'
[2025-03-21T17:50:24.789+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T17:50:26.019+0000] {python.py:240} INFO - Done. Returned value was:                datetime  ...                                id
0   2025-03-22 00:00:00  ...  d141d7863df92d8589c38ada109e123d
1   2025-03-22 01:00:00  ...  9a76c33fd475d3dd15980ea9b0a6cf0f
2   2025-03-22 02:00:00  ...  bcecc2bcc96510667af038521c26a926
3   2025-03-22 03:00:00  ...  bfbcf0e41660e298c99997d3d53d7d1c
4   2025-03-22 04:00:00  ...  b50fabebec04f1c1ceae4f21a3c1fe62
..                  ...  ...                               ...
163 2025-03-28 19:00:00  ...  82bace31ccf535a12c230bd007e74e1f
164 2025-03-28 20:00:00  ...  68940bd488f1bb0d6b44dbc73aa42ae7
165 2025-03-28 21:00:00  ...  296be3fd5649c23a50f62c2636cca692
166 2025-03-28 22:00:00  ...  8757850d378d2c1fe6084046eab4c105
167 2025-03-28 23:00:00  ...  4dd715704408015a5d87f3a0c5434ae6

[168 rows x 6 columns]
[2025-03-21T17:50:26.748+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T17:50:26.751+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-two-source, task_id=fetch_weather_openmeteo, run_id=scheduled__2025-03-21T16:00:00+00:00, execution_date=20250321T160000, start_date=20250321T175023, end_date=20250321T175026
[2025-03-21T17:50:27.137+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T17:50:27.713+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T17:50:27.716+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
