[2025-03-21T17:42:10.194+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T17:42:10.294+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.check_and_insert_data manual__2025-03-21T17:41:52.732921+00:00 [queued]>
[2025-03-21T17:42:10.350+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.check_and_insert_data manual__2025-03-21T17:41:52.732921+00:00 [queued]>
[2025-03-21T17:42:10.352+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T17:42:10.426+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): check_and_insert_data> on 2025-03-21 17:41:52.732921+00:00
[2025-03-21T17:42:10.458+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=176) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T17:42:10.467+0000] {standard_task_runner.py:72} INFO - Started process 178 to run task
[2025-03-21T17:42:10.467+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'check_and_insert_data', 'manual__2025-03-21T17:41:52.732921+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmpgt802w0x']
[2025-03-21T17:42:10.483+0000] {standard_task_runner.py:105} INFO - Job 58: Subtask check_and_insert_data
[2025-03-21T17:42:11.593+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.check_and_insert_data manual__2025-03-21T17:41:52.732921+00:00 [running]> on host c25e9da6226b
[2025-03-21T17:42:11.755+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='check_and_insert_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T17:41:52.732921+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T17:41:52.732921+00:00'
[2025-03-21T17:42:11.757+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T17:42:11.797+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-21T17:42:13.140+0000] {taskinstance.py:3313} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather-data-pipeline.py", line 99, in check_and_insert_data
    cur.executemany(insert_query, new_data.values.tolist())
psycopg2.errors.DatatypeMismatch: column "datetime" is of type timestamp without time zone but expression is of type numeric
LINE 3:         VALUES ('2025-03-22T00:00:00'::timestamp, 26.8, 'Jak...
                                                          ^
HINT:  You will need to rewrite or cast the expression.

[2025-03-21T17:42:13.170+0000] {taskinstance.py:1226} INFO - Marking task as UP_FOR_RETRY. dag_id=weather-data-pipeline, task_id=check_and_insert_data, run_id=manual__2025-03-21T17:41:52.732921+00:00, execution_date=20250321T174152, start_date=20250321T174210, end_date=20250321T174213
[2025-03-21T17:42:13.286+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T17:42:13.288+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 58 for task check_and_insert_data (column "datetime" is of type timestamp without time zone but expression is of type numeric
LINE 3:         VALUES ('2025-03-22T00:00:00'::timestamp, 26.8, 'Jak...
                                                          ^
HINT:  You will need to rewrite or cast the expression.
; 178)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3006, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 274, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3161, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3185, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 768, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 734, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 424, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/weather-data-pipeline.py", line 99, in check_and_insert_data
    cur.executemany(insert_query, new_data.values.tolist())
psycopg2.errors.DatatypeMismatch: column "datetime" is of type timestamp without time zone but expression is of type numeric
LINE 3:         VALUES ('2025-03-22T00:00:00'::timestamp, 26.8, 'Jak...
                                                          ^
HINT:  You will need to rewrite or cast the expression.

[2025-03-21T17:42:13.361+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-03-21T17:42:13.781+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T17:42:13.784+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
